name: Workflow Deployment

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-homologacao:
    name: Deploy para Homologação
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: homologacao
      url: https://farol-devocional-api-hom.onrender.com
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Acionar Deploy Hook em Homologação
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_HOM }}

  deploy-producao:
    name: Deploy para Produção
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: producao
      url: https://farol-devocional-api.onrender.com
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Acionar Deploy Hook no Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_PRD }}