name: Workflow Snapshot

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Selecione a branch base para o build e teste'
        required: true
        type: string
      run_sonar:
        description: 'Executar análise do Sonar'
        type: boolean
        default: false

jobs:
  build-test-feature:
    name: Build e Teste da Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da branch ${{ github.event.inputs.branch_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build e Testes com Maven
        run: mvn -B clean verify

      - name: Análise com SonarCloud
        if: success() && github.event.inputs.run_sonar == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=fessrodrigues_${{ github.event.repository.name }} \
            -Dsonar.organization=fessrodrigues \
            -Dsonar.host.url=https://sonarcloud.io